export const commentData = [
    {
        commentid: "c001",
        tweetid: "t001",
        authorid: "u101",
        authorname: "Alice Johnson",
        authorusername: "alicej",
        content: "Just had the best coffee ever! ☕️ #blessed",
        commentData: {
            commentid: "c001dsasd",
            tweetid: "t001dsfas",
            authorid: "u101adsda",
            authorname: "Abhishek Yadav",
            authorusername: "alicej",
            content: "Hello i am abhishek yadav , and  project",
            commentData: {
                commentid: "c001dsasd",
                tweetid: "t001dsfas",
                authorid: "u101adsda",
                authorname: "Abhishek Yadav",
                authorusername: "alicej",
                content: "Hello i am abhishek yadav , and shoutout project",
                commentData: {
                    commentid: "c001",
                    tweetid: "t001",
                    authorid: "u101",
                    authorname: "Alice Johnson",
                    authorusername: "alicej",
                    content: "Just had the best coffee ever! ☕️ #blessed",
                    commentData: {
                        commentid: "c001",
                        tweetid: "t001",
                        authorid: "u101",
                        authorname: "Alice Johnson",
                        authorusername: "alicej",
                        content: "Just had the best coffee ever! ☕️ #blessed",
                    },
                },
            },
        },
    },
    {
        commentid: "c001",
        tweetid: "t001",
        authorid: "u101",
        authorname: "Alice Johnson",
        authorusername: "alicej",
        content: "Just had the best coffee ever! ☕️ #blessed",
        commentData: {
            commentid: "c001dsasd",
            tweetid: "t001dsfas",
            authorid: "u101adsda",
            authorname: "Abhishek Yadav",
            authorusername: "alicej",
            content: "Hello i am abhishek yadav , and  project",
            commentData: {
                commentid: "c001dsasd",
                tweetid: "t001dsfas",
                authorid: "u101adsda",
                authorname: "Abhishek Yadav",
                authorusername: "alicej",
                content: "Hello i am abhishek yadav , and shoutout project",
                commentData: {
                    commentid: "c001",
                    tweetid: "t001",
                    authorid: "u101",
                    authorname: "Alice Johnson",
                    authorusername: "alicej",
                    content: "Just had the best coffee ever! ☕️ #blessed",
                    commentData: {
                        commentid: "c001",
                        tweetid: "t001",
                        authorid: "u101",
                        authorname: "Alice Johnson",
                        authorusername: "alicej",
                        content: "Just had the best coffee ever! ☕️ #blessed",
                    },
                },
            },
        },
    },
];
